const data = {
    "Back Office": {
        "Financial": {
            "Exceptional Callback": "we don't assign this request from Call center Now"
        },
        "Non Financial": {
            "Call back": "we don't assign this request from Call center Now"
        },
        "Follow up": {
            "Bonus": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "Cash on phone": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "Closure requests": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "Debit/credit card replacement": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "Limit transfer / requests": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "Secure code": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "Smart wallet": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "charge back": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "checkbook request delay": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`,
            "incomplete transaction": `<span class="important-note">Requirements:</span><br>- Agent assign the follow up task  instead of sending email to back office team.<br>- TAT 1 WD<br><span class="important-note">NOTE:</span><br>- Consolidated notification mail from back office team will be sent to agents notifying them that feedback were updated over CRM to check it.`
        }
    },
    "Business Banking": {
        "SS BB Account": {
            "BB Change Statement Frequency": "Not related for Call center Inbound agent",
            "BB Change Statement Type": "Not related for Call center Inbound agent"
        },
        "SS BB Credit Card": {
            "BB CC change DD percentage": "Not related for Call center Inbound agent"
        },
        "SS BB Online": {
            "Adding ACC Over FBCC": "Not related for Call center Inbound agent",
            "Adding CC Over FBCC": "Not related for Call center Inbound agent"
        }
    },
    "Service Request": {
        "KYC": {
            "Updating KYC Notification": `<span class="important-note">Requirements:</span><br>-The call must be from the registered mobile number <br>-If the customer has assigned the request before, we can’t re-assign it. <br>- Advise the Customer: Inform them that if they do not update their data within 3 working days, a posting restriction will be placed on their account, blocking transactions.<br>- Instructions: Direct the customer to visit a branch with the required documents to update their KYC.<br>- Exception: A temporary exception to this restriction can be made only for urgent transfers.<br>- Wrap Up: Always complete the wrap-up procedure after any KYC inquiry.<br>- How to Assign the Task: <br>- TAT The same day or send to SV mail to speed up the process.<br>- The agent must assign a KYC request and use the following template in the description field: <br><br>Appreciate your Support to remove the KYC restriction for the below account.<br><br>Reason of Exception:<br>Customer Name:<br>Customer Number:<br>Customer Segment:<br>Mobile #<br>Calling Party:<br><span class="important-note">NOTE:</span><br>- 2.Supervisor will Send email to get the needed approval to remove the restrictions<br>- 3. After obtaining the approval , Supervisor will sent email to the agent to proceed the action from T24 then supervisor will authorize the action<br>- 4. Supervisor will assign FCR Complaint on CRM with the action taken`
        },
        "SS Acquiring": {
            "Acquirin Credit & Debit Advise": `<span class="important-note">Requirements:</span><br>- These are the opposite of a chargeback.<br><br>Details required: merchant Mobile Number, merchant email.<br><br>Debit Request:<br><br>Example: the transaction amount should be 100 EGP, but the merchant charged 1,000 EGP.<br><br>The difference (900 EGP) must be returned to the customer.<br><br>You create a debit request in the smart script system.<br><br>Credit Request:<br><br>Example: the transaction should be 10,000 EGP, but only 1,000 EGP was charged.<br><br>The merchant needs to collect the remaining 9,000 EGP.<br><br>This is handled as a credit request, also through a form sent by email.<br><br>The customer must provide a receipt of the original transaction.<br><br> TAT for this request : 1 WD<br><span class="important-note">NOTE:</span><br>- Debit Request → refund to the customer (overcharged).<br>- Credit Request → collect remaining amount from customer (undercharged).<br>- Back office team sends a form to the merchant to fill and confirm.`,
            "Acquiring - Merchant": `<span class="important-note">Requirements:</span><br>- 1-When a transaction is accepted in the system (it has a valid authorization code), but the merchant’s POS doesn’t show it, the process is as follows:<br>- 2-We assign this request to releasethis transaction from our side and informe the merchant to do this Transaction again <br><span class="important-note">NOTE:</span><br>- TAT:3 WD`
        },
        "SS Address": {
            "CMA - Account": `<span class="important-note">Requirements:</span><br>- Clearly state exception reason in request (Senior, Overseas, etc.)<br>- National ID must be valid on T24 (7-year validity rule, 1-day variance acceptable on expiry)<br>- Foreigners: Only passport must be valid<br>- Customer contacted on registered mobile only (from T24/Card400)<br>- All registered data (ID/Passport) must be valid regardless of nationality <br>-If customer have both NID and passport, both need to be valid or the task will be rejected. (For all CMA requests.) <br>- TAT: 2 WD.<br><span class="important-note">NOTE:</span><br>- CMA Request ONLY in these 4 cases:<br>- Senior Customers (60+ years)<br>- Primary card holders changing Mobile number for supplementary cards<br>- Overseas Customers<br>- Remove +2/002 from mobile number<br><br>For Senior Customers:<br>- Outbound team will contact on registered mobile only<br>- No IVR subscription allowed<br>For Overseas Customers:<br>- IVR subscription required (customer must be identified through IVR login ID or conference call with IVR)<br><br>Special Cases:<br>- CMA with Replacement:<br>- For customers needing replacement card sent to new address<br>- Must verify replacement conditions first<br>- Add card number, masked card, replacement reason in smart script`,
            "CMA - Credit Card": `<span class="important-note">Requirements:</span><br>- Clearly state exception reason in request (Senior, Overseas, etc.)<br>- National ID must be valid on T24 (7-year validity rule, 1-day variance acceptable on expiry)<br>- Foreigners: Only passport must be valid<br>- Customer contacted on registered mobile only (from T24/Card400)<br>- All registered data (ID/Passport) must be valid regardless of nationality<br>-If customer have both NID and passport, both need to be valid or the task will be rejected. (For all CMA requests.)<br>- TAT: 2 WD.<br><span class="important-note">NOTE:</span><br>- Now, we didn’t assign this request because we don’t have the authority to update on Cortex or Card400.<br>- Please check if the customer needs to update the address on Card400 and if the same address exists in T24. If so, please advise the customer to update it through Internet Banking (IB).<br><br>- If the customer needs to update the address on Card400 but the address is not in T24,<br>- please inform the customer that we will change all registered addresses and assign the request to (CMA – Account).<br>- The change will be reflected in T24 first, and then in Card400.`,
            "CMA.- Wealth-Account": `<span class="important-note">Requirements:</span><br>- This request Special for Wealth & Private Customer <br>- Clearly state exception reason in request  ( Senior, Overseas, etc.)<br>- National ID must be valid on T24 (7-year validity rule, 1-day variance acceptable on expiry)<br>- Foreigners: Only passport must be valid<br>- Customer contacted on registered mobile only (from T24/Card400)<br>- All registered data (ID/Passport) must be valid regardless of nationality <br>-If customer have both NID and passport, both need to be valid or the task will be rejected. (For all CMA requests.)<br>- TAT: 2 WD.<br><span class="important-note">NOTE:</span><br>- CMA Request ONLY in these 4 cases:<br>- Senior Wealth & Private Customers (60+ years)<br>- Primary card holders changing Mobile number for supplementary cards<br>- Wealth & Private Overseas Customers<br>- Remove +2/002 from mobile number<br><br>For Wealth & Private Senior Customers:<br>- Outbound team will contact on registered mobile only<br>- No IVR subscription allowed<br>For Overseas Customers:<br>- IVR subscription required (customer must be identified through IVR login ID or conference call with IVR)<br><br>Special Cases:<br>- CMA with Replacement:<br>- For customers needing replacement card sent to new 
address<br>- Must verify replacement conditions first<br>- Add card number, masked card, replacement reason in smart script`,
            "CMA.-Wealth - Credit Card": `<span class="important-note">Requirements:</span><br>- This request Special for Wealth & Private Customer <br>- Clearly state exception reason in request  ( Senior, Overseas, etc.)<br>- National ID must be valid on T24 (7-year validity rule, 1-day variance acceptable on expiry)<br>- Foreigners: Only passport must be valid<br>- Customer contacted on registered mobile only (from T24/Card400)<br>- All registered data (ID/Passport) must be valid regardless of nationality <br>-If customer have both NID and passport, both need to be valid or the task will be rejected. (For all CMA requests.)<br>- TAT: 2 WD.<br><span class="important-note">NOTE:</span><br>- Now, we didn’t assign this request because we don’t have the authority to update on Cortex or Card400.<br>- Please check if the customer needs to update the address on Card400 and if the same address exists in T24. If so, please advise the customer to update it through Internet Banking (IB).<br><br>- If the customer needs to update the address on Card400 but the address is not in T24,<br>- please inform the customer that we will change all registered addresses and assign the request to ( CMA.- Wealth-Account ).<br>- The change will be reflected in T24 first, and then in Card400.`,
            "CMA - Supplementary": `<span class="important-note">Requirements:</span><br>- For supplementary card mobile number updates only<br>- Cannot proceed if the supplementary card holder has their own primary credit card at CIB.<br>- National ID must be valid on T24 (7-year validity rule, 1-day variance acceptable on expiry)<br>- Foreigners: Only passport must be valid<br>- Customer contacted on registered mobile only (from T24/Card400)<br>- All registered data (ID/Passport) must be valid regardless of nationality <br>-If customer have both NID and passport, both need to be valid or the task will be rejected. (For all CMA requests.)<br>- TAT: Next WD<br><span class="important-note">NOTE:</span><br>- Customer will not be contacted again<br>- Add new mobile in Additional Telephone# field<br>- Add supplementary masked card in task description<br>- Must add the supplementary Sema in Smart script ⇉ (Shift+F5)+(Shift+F9) Cardholder: XXXXXX `
        },
        "SS Cards": {
            "Bank Assurance - Credit Card": `<span class="important-note">Requirements:</span><br>- This request is used to end the subscription of old insurance programs that were subscribed to on a credit card, such as the Family Protection Program.<br><span class="important-note">NOTE:</span><br>- TAT :3 WD`,
            "Card Deliv. bet. Branches-ACC": `<span class="important-note">Requirements:</span><br>- Confirm that card is already available at the branch through hold mail sheets OR Courior <br>- In the event that the customer requests to transfer the card, checkbook,  he wants from one branch to another<br><span class="important-note">NOTE:</span><br>- You should make sure that the card or cheque book is in the branch not in DCU or not hold to be sent to customer’s address. ( The card or  cheque book must be physically present at the branch )<br>- TAT: 3 WDs`,
            "Card Deliv. bet. Branches-CC": `<span class="important-note">Requirements:</span><br>- Confirm that card is already available at the branch through hold mail sheets OR Courior <br>- In the event that the customer requests to transfer the Credit card he wants from one branch to another<br><span class="important-note">NOTE:</span><br>- You should make sure that the card is in the branch not in DCU or not hold to be sent to customer’s address. ( The card must be physically present at the branch ) . <br>- TAT: 3 WDs`,
            "Card not recognized": `<span class="important-note">Requirements:</span><br>- A customer reports their new debit card is not working. Upon checking, the transaction history (IST) shows:<br>- Transactions are available only from non-CIB ATMs.<br>- No transaction attempts are visible from CIB ATMs.<br>- TAT 2 WD<br><span class="important-note">NOTE:</span><br>- A replacement card will be issued for free.`,
            "Cards Closure Request": `<span class="important-note">Requirements:</span><br>- Account agreement status 09 active card<br><span class="important-note">NOTE:</span><br>- advise customer that he would receive call from concerned department within 2-3 WD <br>-Need to mention that if the card has inactive Spend Customer note on card notes (Shift + F2), then he will not receive a call and the card will be closed without call`,
            "Cards Delivery Request-Account": `<span class="important-note">Requirements:</span><br>- 1-Validate card Exedit TAT or not ( Al TAT in Not )<br>- 2-Get Shipment number <br>- 3-start search On DCU sheet <br>- 4-If you didn't find any result So refer back to Courier Linke If you See (Undeliverd - Intranset …....)<br>- 5-OR if you see IN DCU ( Delivery Task ) so Search with the DCU refernce ( New Policy ) in the courier link before assigning Delivery Task to make Sure Card didn't deliverd <br>- 6-All instractions On DCU sheet Just follow The steps <br><span class="important-note">NOTE:</span><br>- TAT For Delivery Task<br>- Premium Cards  ( Platinum  ) New & Replacment 2 WD inside Cairo/ 4 WD outside<br>- Core ( Any card without Platinum  ) New & Replacement 5 WD inside Cairo / 7 WD outside<br>- Normal TAT for Delivery ( When the card issued ) the same this TAT but If card Renewal All Cards 15 WD `,
            "Cards Delivery Request-CC": `<span class="important-note">Requirements:</span><br>- 1-Validate card Exedit TAT or not ( Al TAT in Not )<br>- 2-Get Shipment number ( Shift +F2 )<br>- 3-start search On DCU sheet <br>- 4-If you didn't find any result So refer back to Courier Linke If you See (Undeliverd - Intranset …....)<br>- 5-OR if you see IN DCU ( Delivery Task ) so Search with the DCU refernce ( New Policy ) in the courier link before assigning Delivery Task to make Sure Card didn't deliverd <br>- 6-All instractions On DCU sheet Just follow The steps <br><span class="important-note">NOTE:</span><br>- TAT For Delivery Task<br>- Premium Cards  ( Platinum  ) New & Replacment 2 WD inside Cairo/ 4 WD outside<br>- Core ( Any card without Platinum  ) New & Replacement 5 WD inside Cairo / 7 WD outside<br>- Normal TAT for Delivery ( When the card issued ) the same this TAT but If card Renewal All Cards 15 WD `,
            "Cash On Phone": `<span class="important-note">Requirements:</span><br>- Eligibility Restrictions - NOT Allowed if:<br>- 1. Expired <br>- 2. Insufficient amount<br>- 3. Customer has arrears<br>- 4. Card has stop code<br>- 5. Inactive account<br>- 6. Post restricted account<br>- 7. Expired credit card<br>- 8. CM has no active card<br>- 9. Direct Debit doesn't match Card400<br>- 10. Over payment <br>- 11. Refer KYC<br><span class="important-note">NOTE:</span><br>- Amount must be written...in numbers with NO decimals.. (e.g., 1485 ✓, 1485.25 ✗)<br>- Tenor must be written ..in numbers only.. (e.g., 12 ✓, 12M ✗)<br><br>- 2-For SWYPE Cards:<br>- Must add Campaign Name >> in description:<br>  - B12 - SWYPE 12 (2.67%) - 12 Months (Min: 1000)<br>  - B36 - SWYPE 36 (2.67%) - 36 Months (Min: 2000)<br>  - B60 - SWYPE 60 (2.67%) - 60 Months (Min: 3000)<br>  -BS1 - SWYPE 12 STAFF (2.00%) - BS1 12 months STAFF<br>  -BS2 - SWYPE 36 STAFF (2.00%) - BS2 36 months  STAFF<br>  -BS3 - SWYPE 60 STAFF (2.00%) - BS3 60 months  STAFF<br>- Tenor *must match card type* (e.g., Swype 12 → tenor 12)<br>-For Staff Cards:<br>- Campaign ID 101 for 6M-36M<br>- 3-Branch Collection:<br>If no Direct Debit account, customer can collect from:<br>- Maadi Towers<br>- El Gezira<br>- Mostafa El Nahas<br>- El Azarita branches<br>- Write branch name & code in ACCOUNT # box<br><br>- 4-Special Cases:<br>- If COP request pending → assign follow-up, NOT new request<br>- If Direct Debit closed but customer has other active account → advise to change via IB`,
            "Change Credit Card Product": `<span class="important-note">Requirements:</span><br>- The card expires in more than 6 months.<br>- The card's credit limit is eligible for the new product (e.g., Platinum requires 30K).<br>- The account has no arrears and is not over its limit.<br>* The "No Major Changes" Rule:<br>- The request is only for a simple upgrade/downgrade. The following changes are NOT allowed:<br>- Changing the billing cycle (e.g., from 55 days to 45 days).<br>- Switching the payment network (e.g., Visa to Mastercard).<br>- Changing the rewards program (e.g., Bonus points to Miles).<br>- Fees of 150 EGP will be deducted<br><span class="important-note">NOTE:</span><br>- Special Case: Swype Cards<br>- A Swype card can only be changed to another Swype card, not to any other standard or special program card.<br>- Customer can use the old card within the TAT, and the Old card will stop only if the customer activate the new card.<br>- This request will not affect the international card limit.<br>- If the card is not activated within 3 months, the new card will be stopped and can’t be activated again.<br>- TAT: 10 WDs`,
            "Change Credit Card Type": `<span class="important-note">Requirements:</span><br>- This request available to change from Type to other Type Like From Gold To Noon or From platinaum to SWYPE ....<br>- Card limit is Eligible for the new type... Like:( platinaum 30K / World 100K ) <br>- Card should not have EPP (EPP should be canceled)<br>- Card should have one card type product only under the customer sema ..Like:If CM have CC Noon we can't Cahnge Other Type to Noon<br>- Card should not have amounts in hold that need to be released first to proceed<br>- Cash Back Cards: Any card can be changed to a Cash Back card if it meets the criteria. However, only customers with a single card are eligible for this product.<br>- World Elite Cards: These are only available to Private Wealth or Wealth customers.<br><br><span class="important-note">NOTE:</span><br>- The customer will not lose his old credit card points & it will be on hold till he activates the new received card & make one purchase transaction<br>-  Customer will be charged by ( annual fees ) related to the new card type <br>- Fee Charged, Then Immediate Change: If a customer is charged a renewal fee and then requests a new card type, they will be charged a  ( second annual fee ) for the new card as soon as they activate it.<br>- Change Before Renewal Date: If a customer changes their card type before their( renewal date ) , they will be charged the new card's ( annual fee) shortly after activation, without waiting for the original renewal date.<br>- Delayed Activation: If a customer requests a new card but ( doesn't activate it ) until much later, they will be charged ( twice ) in the same period: once for the renewal of the old card and once for the activation of the new card.<br>-The New card can benefit with international limit after 2 months not before.( The old card will be stopped and the customer has to wait until he receives and activate the new card ) but Need to mention that the customer can use international limit if he has any other other active card.<br>- TAT: 10 WDs`,
            "Credit Card Replacement": `<span class="important-note">Requirements:</span><br>- NOT Eligible if:<br>- Card blocked for Collections or Fraud reasons<br>- Card is overlimit ( >105% tolerance)<br>- Has AFU notes prohibiting replacement<br>- Has Override codes: HOR (hold release), PRW (pending renewal), SST (stop statement)<br>- Card closed for over 6 months (advise customer to submit new application)<br>- Exception: Can replace if card number closed >6 months but Card400 account still active<br>- Arrears Status:<br>- 30+ days: Customer must pay first, then call back<br>- 60+ days: Customer must pay, then refer to branch<br>- 90+ days: Card cannot be reopened<br>- (TAT): 2 Working Days<br><span class="important-note">NOTE:</span><br>- Cards are typically replaced with same expiry date<br>- Agent can assign with ""Extend Expiry Date"" in description if customer requests (even if card expires in >3 months)<br>- For expired cards with active accounts: replacement allowed<br>- For expired cards with inactive accounts: refer to branch (within 6 months of closing, agreement status 10/11 only)<br>- Special Cases:<br>- Supplementary cards about to expire: Replace primary card with new expiry (after confirmation), supplementaries get expiry extension<br>- Replacing closed supplementary card after product change: Submit Supplementary Referral, NOT replacement request<br>- Cards terminated from DCU >90 days with active account: Contact Center can replace<br>- For agreement status 10, 11 & 12: Customer must submit new CC application`,
            "Credit Limit Decrease": `<span class="important-note">Requirements:</span><br>- TAT :2-3 WD <br>- New limit must be equal or more than the current balance<br>- New limit must be within limit range of the card type "" For example, a Platinum card cannot be decreased below 30K.""<br><span class="important-note">NOTE:</span><br>- (Ex: you can’t assign the request for titanium card if the customer wants to make his Titanium card with 9K as the minimum limit of Titanium card is 10K)<br>- Agent must inform the customer that he can’t apply for limit increase only after after 6  month to  1 Year  of the request throw branch `,
            "Card Activation Exception": `<span class="important-note">Requirements:</span><br>-The request will be assigned In Case activation done by call center agent on the below two scenarios:<br>1-Customer tried all activation channels (IVR-ATM-IB/MB-SMS) and faced technical error (All segments except private customers)<br>2-Private Supplementary credit cards activation . <br><span class="important-note">NOTE:</span> <br>-The customer must mention that they tried all activation channels (IVR-ATM-IB/MB-SMS) during the same call, but faced a technical error.`,
            "D.D Instructions - CBE - CC": "No more used",
            "D.D Process-Interest Waiver-CC": "No more used",
            "Debit Card Replacement": `<span class="important-note">Requirements:</span><br>- Card status Should be (Normal ,Warm, Pin runup, Stolen) <br>- KYC must be valid ( if not please refer customer to the branch to update his data) <br>- Account status should be (Normal ,ACTIVE, True “ in Cortex “, No Refer Debit )<br>-If the card was systematically renewed with a different number, make sure to replace the new card details, even if the physical card hasn't been printed. <br>- TAT 2 WD<br><span class="important-note">NOTE:</span><br>- Check the Address: First, verify the customer's communication address. If it is not clear, advise them to update it or choose to have the card sent to a branch.<br>- Delivery to a Branch:<br>- In the smart script, select YES.<br>- You must fill out the next field with the exact ""Branch Name & Address / Branch city"".<br>- Delivery to Mailing Address:<br>- In the smart script, select NO.<br>- You can ignore the ""Branch Name & Address"" field. There is no need to fill it in.`,
            "FX Limit Exception": `<span class="important-note">Requirements:</span><br>- Request only after 2 months from card issuance <br>- If the customer has any other active cards for more than 2 months, then the agent can proceed normally with the request.<br>- Amount depends on customer segment<br>- International limit excludes markup fees<br>- Add full credit card number in detailed description (don't fill smart script details)<br>- If customer has multiple cards with same ending and refuses to provide full number, add embossing name with masked card<br>- TAT: 2 WD (customer receives SMS when limit opened)<br><span class="important-note">NOTE:</span><br>- Customer mustn't provide departure Unlesse the bank Asking Him / her  to provide departure<br>- Don't assign new FX limit if old exception expiration >1 WD (extension valid only if remaining period ≤1 day)<br>- If card blocked, direct customer to branch to resubmit documents<br>- If segment upgraded but not reflected, add note ""Override existing limit"" with card number`,
            "Limit Transfer bet. Cards-CC": `<span class="important-note">Requirements:</span><br>- For active cards, the minimum amount eligible for a transfer is 500 EGP.<br>- The refunded amount must be over the customer's credit limit.<br>- Refunded amounts should be backed on original trnxs (Ex. If Souq.com made a refund but there was not trnx before from Souq request not to be assigned). Check the remaining Special scenarios from this Link <br>- (TAT): 2-3 Working Days<br><span class="important-note">NOTE:</span><br>- If the amount is less than 500 EGP, the agent must advise the customer to simply use the balance on their active card, as it is a small amount.<br>- Non-Refundable Amounts: The following types of credits/refunds cannot be processed for a limit transfer: ( Bonus cashback - Cashback from CLCU -PayPal refunds )`,
            "Merge Credit Cards": `<span class="important-note">Requirements:</span><br>- Card Type: Both cards must be Secured cards. The agent must verify this by checking the Card 400 system and the CRM (Financial Summary – Deposits).<br>- Swyp & talabat Cards: Not eligible for merging under any circumstances, even if they are secured.<br>- Old Card Status: The old card (to be merged and closed) must have:<br>- No amount on hold.<br>- No active installments.<br>- New Card Limit: The new card (which will remain open) must be eligible for the increased limit resulting from the merge.<br>- TAT: 3WDs<br><span class="important-note">NOTE:</span><br>- (Ex: if the customer has 2 titanium credit cards with 100K and 70K we can’t proceed as the new card limit will be 170K and the Titanium’s maximum card limit is 150K)<br>- The bonus of the old card will Expire.`,
            "Merge Unsecured Credit Cards": `<span class="important-note">Requirements:</span><br>- Card Type: Both cards must be unsecured cards. The agent must verify this by checking the Card 400 system and the CRM (Financial Summary – Deposits).<br>- Swyp & talabat Cards : Not eligible for merging under any circumstances, even if they are unsecured.
<br>- You need to insert the LO number for both cards in the Smart Script (Old LO Application & New LO Application) fields. You can find it on the ( Shift+F1 ) screen over the Card400 system; the LO will be at the end of the page.
<br>- Old Card Status: The old card (to be merged and closed) must have:<br>- No amount on hold.<br>- No active installments.<br>- New Card Limit: The new card (which will remain open) must be eligible for the increased limit resulting from the merge.<br>- TAT: 3WDs<br><span class="important-note">NOTE:</span><br>- (Ex: if the customer has 2 titanium credit cards with 100K and 70K we can’t proceed as the new card limit will be 170K and the Titanium’s maximum card limit is 150K)<br>- The bonus of the old card will Expire.`,
            "Missing Delivery - ACC": `<span class="important-note">Requirements:</span><br>- The card must not have a ""Hold Mail"" .<br>- The card must not have been ""Sent to Branch"".<br>- The agent must validate that all standard delivery conditions have been met and the card is still missing.<br><span class="important-note">NOTE:</span><br>-We can't Trace the card after 3 Months of Issuance
 <br>-New Cards : Request to be assigned within 3 months of card issuance date. <br>-Renewal Cards: Request to be assigned after 2 weeks of renewal month till 3 months delay.
<br>- If the card is missing after validation, assign the request.<br>- TAT: 3WDs`,
            "Missing Delivery - CC": `<span class="important-note">Requirements:</span><br>- The card must not have a ""Hold Mail"" .<br>- The card must not have been ""Sent to Branch"".<br>- The agent must validate that all standard delivery conditions have been met and the card is still missing.<br><span class="important-note">NOTE:</span> <br>-We can't Trace the card after 3 Months of Issuance<br>-New Cards : Request to be assigned within 3 months of card issuance date. <br>-Renewal Cards: Request to be assigned after 2 weeks of renewal month till 3 months delay.<br>Agent must check the English address in card 400 , as it may be registered as hold mail in branch .<br>Agent should not fill the Policy (as it missed)and the Address fields in Smart Script
<br>- If the card is missing after validation, assign the request.<br>- TAT: 3WDs`,
            "Private - Cards Delivery-CC": `<span class="important-note">Requirements:</span><br>- only sent when private customer need to deliver the card in an unregistered address without change the existing one.<br>- 1-Customer MUST contact the Call Center from his registered mobile number.<br>- 2-You MUST inform the Customer that he will receive another call from Outbound Team Agent to complete the process after full verification.<br>- 3-Outbound Team will direct the request after validation either to DCU or Courier Company as per card location.<br>- After that validate the requirements of the normal Delivery<br>- 1-Validate card Exedit TAT or not ( Al TAT in Not )<br>- 2-Get Shipment number ( Shift +F2 )<br>- 3-start search On DCU sheet <br>- 4-If you didn't find any result So refer back to Courier Linke If you See (Undeliverd - Intranset …....)<br>- 5-OR if you see IN DCU ( Delivery Task ) so Search with the DCU refernce ( New Policy ) in the courier link before assigning Delivery Task to make Sure Card didn't deliverd <br>- 6-All instractions On DCU sheet Just follow The steps <br><span class="important-note">NOTE:</span><br>- TAT For Delivery Task<br>- Premium Cards  ( Platinum  ) New & Replacment 2 WD inside Cairo/ 4 WD outside<br>- Core ( Any card without Platinum  ) New & Replacement 5 WD inside Cairo / 7 WD outside<br>- Normal TAT for Delivery ( When the card issued ) the same this TAT but If card Renewal All Cards 15 WD `,
            "Private -Returned Cards-CC": `<span class="important-note">Requirements:</span><br>- only sent when private customer need to deliver the card in an unregistered address without change the existing one.<br>- 1-Customer MUST contact the Call Center from his registered mobile number.<br>- 2-You MUST inform the Customer that he will receive another call from Outbound Team Agent to complete the process after full verification.<br>- 3-Outbound Team will direct the request after validation either to DCU or Courier Company as per card location.<br>- After that validate the requirements of the normal Delivery<br>- 1-Validate card Exedit TAT or not ( Al TAT in Not )<br>- 2-Get Shipment number <br>- 3-start search On DCU sheet <br>- 4-If The card is Credit In DCU make sure that the Policy same Fake ACC on DCU sheet but CC Fake Account # on Card 400 (F5)<br>- 5-If you didn't find any result So refer back to Courier Linke If courier’s link feedback is Returned on the same day of task or the day before and card still not found in DCU sheet, submit a returned task and add “as per courier link” in Description""<br>- 6-If you will submit a Returned task “as per courier link” you will use Fack ACC on CARD 400 System as Policy <br>- 7-All instractions On DCU sheet Just follow The steps <br><span class="important-note">NOTE:</span><br>- TAT For Delivery Task<br>- Premium Cards  ( Platinum  ) New & Replacment 2 WD inside Cairo/ 4 WD outside<br>- Core ( Any card without Platinum  ) New & Replacement 5 WD inside Cairo / 7 WD outside<br>- Normal TAT for Delivery ( When the card issued ) the same this TAT but If card Renewal All Cards 15 WD `,
            "Private Cards Delivery-Account": `<span class="important-note">Requirements:</span><br>- only sent when private customer need to deliver the card in an unregistered address without change the existing one.<br>- 1-Customer MUST contact the Call Center from his registered mobile number.<br>- 2-You MUST inform the Customer that he will receive another call from Outbound Team Agent to complete the process after full verification.<br>- 3-Outbound Team will direct the request after validation either to DCU or Courier Company as per card location.<br>- After that validate the requirements of the normal Delivery<br>- 1-Validate card Exedit TAT or not ( Al TAT in Not )<br>- 2-Get Shipment number <br>- 3-start search On DCU sheet <br>- 4-If you didn't find any result So refer back to Courier Linke If you See (Undeliverd - Intranset …....)<br>- 5-OR if you see IN DCU ( Delivery Task ) so Search with the DCU refernce ( New Policy ) in the courier link before assigning Delivery Task to make Sure Card didn't deliverd <br>- 6-All instractions On DCU sheet Just follow The steps <br><span class="important-note">NOTE:</span><br>- TAT For Delivery Task<br>- Premium Cards  ( Platinum  ) New & Replacment 2 WD inside Cairo/ 4 WD outside<br>- Core ( Any card without Platinum  ) New & Replacement 5 WD inside Cairo / 7 WD outside<br>- Normal TAT for Delivery ( When the card issued ) the same this TAT but If card Renewal All Cards 15 WD `,
            "Private-Returned Cards-ACC": `<span class="important-note">Requirements:</span><br>- only sent when private customer need to deliver the card in an unregistered address without change the existing one.<br>- 1-Customer MUST contact the Call Center from his registered mobile number.<br>- 2-You MUST inform the Customer that he will receive another call from Outbound Team Agent to complete the process after full verification.<br>- 3-Outbound Team will direct the request after validation either to DCU or Courier Company as per card location.<br>- After that validate the requirements of the normal Delivery<br>- 1-Validate card Exedit TAT or not ( Al TAT in Not )<br>- 2-Get Shipment number <br>- 3-start search On DCU sheet <br>- 4-If you didn't find any result So refer back to Courier Linke If courier’s link feedback is Returned on the same day of task or the day before and card still not found in DCU sheet, submit a returned task and add “as per courier link” in Description""<br>- 5-If you will submit a Returned  you will use ( Big Policy ) on Card issuance Policy <br>- 6-All instractions On DCU sheet Just follow The steps <br><span class="important-note">NOTE:</span><br>- TAT For Delivery Task<br>- Premium Cards  ( Platinum  ) New & Replacment 2 WD inside Cairo/ 4 WD outside<br>- Core ( Any card without Platinum  ) New & Replacement 5 WD inside Cairo / 7 WD outside<br>- Normal TAT for Delivery ( When the card issued ) the same this TAT but If card Renewal All Cards 15 WD `,
            "Re-Print Request - ACC": `<span class="important-note">Requirements:</span><br>- This request for CM to reprint Statement For account ( maximum 3 Months  ) <br>- 1-check statement extension ( address ) or Internet <br>- 2-Customer denied that receiving statement on registered address<br><span class="important-note">NOTE:</span><br>- TAT:3 WD`,
            "Re-Print Request - Credit Card": `<span class="important-note">Requirements:</span><br>- This request for CM to reprint Statement For Credit Card ( maximum 3 Months  ) <br>- 1-check statement extension ( address ) or Internet <br>- 2-Customer denied that receiving statement on registered address<br><span class="important-note">NOTE:</span><br>- TAT:3 WD`,
            "Reinstates Credit Cards - CC": "No more used",
            "Reset Secure Code CC": `<span class="important-note">Requirements:</span><br>- Customer's mobile number must be updated in Card400 system<br>- We need to mention that the full card number is a must to be added in the description.<br>- Card Number:<br>- Card Type (Primary Card / Supplementary Card):<br>- Registered Mobile Number:<br>- Calling Party:<br><span class="important-note">NOTE:</span><br>- For Supplementary cards: Ensure supplementary mobile number is updated on Card400 screen  (Pin Reset Screen)`,
            "Reset Secure Code - DC": `<span class="important-note">Requirements:</span><br>- Customer's mobile number must be updated in T24 system<br>- We need to mention that the full card number is a must to be added in the description.<br>- Card Number:<br>- Card Type (Primary Card / Supplementary Card):<br>- Registered Mobile Number:<br>- Calling Party:<br><span class="important-note">NOTE:</span><br>- For Supplementary cards: Ensure supplementary mobile number is updated on Card400 screen (Pin Reset Screen)`,
            "Returned Cards Delivery-ACC": `<span class="important-note">Requirements:</span><br>- 1-Validate card Exedit TAT or not ( Al TAT in Not )<br>- 2-Get Shipment number <br>- 3-start search On DCU sheet <br>- 4-If you didn't find any result So refer back to Courier Linke If courier’s link feedback is Returned on the same day of task or the day before and card still not found in DCU sheet, submit a returned task and add “as per courier link” in Description""<br>- 5-If you will submit a Returned  you will use ( Big Policy ) on Card issuance Policy <br>- 6-All instractions On DCU sheet Just follow The steps <br><span class="important-note">NOTE:</span><br>- TAT For Delivery Task<br>- Premium Cards  ( Platinum  ) New & Replacment 2 WD inside Cairo/ 4 WD outside<br>- Core ( Any card without Platinum  ) New & Replacement 5 WD inside Cairo / 7 WD outside<br>- Normal TAT for Delivery ( When the card issued ) the same this TAT but If card Renewal All Cards 15 WD `,
            "Returned Cards Delivery-CC": `<span class="important-note">Requirements:</span><br>- 1-Validate card Exedit TAT or not ( Al TAT in Not )<br>- 2-Get Shipment number <br>- 3-start search On DCU sheet <br>- 4-If The card is Credit In DCU make sure that the Policy same Fake ACC on DCU sheet but CC Fake Account # on Card 400 (F5)<br>- 5-If you didn't find any result So refer back to Courier Linke If courier’s link feedback is Returned on the same day of task or the day before and card still not found in DCU sheet, submit a returned task and add “as per courier link” in Description""<br>- 6-If you will submit a Returned task “as per courier link” you will use Fack ACC on CARD 400 System as Policy <br>- 7-All instractions On DCU sheet Just follow The steps <br><span class="important-note">NOTE:</span><br>- TAT For Delivery Task<br>- Premium Cards  ( Platinum  ) New & Replacment 2 WD inside Cairo/ 4 WD outside<br>- Core ( Any card without Platinum  ) New & Replacement 5 WD inside Cairo / 7 WD outside<br>- Normal TAT for Delivery ( When the card issued ) the same this TAT but If card Renewal All Cards 15 WD `,
            "SMS Alert Serv. Not Active-ACC": `<span class="important-note">Requirements:</span><br>- 1-Customer has their registered mobile number<br>- 2-Check SMS History in CRM:<br>- *If SMS appears in history (even with delivery status ""False"") → No action needed<br>- Bank system has sent the SMS, so issue is not from bank side<br>- *If SMS does NOT appear in history:<br>- Assign SMS Alert SR in CRM<br>- Open SD ticket directly<br>- Attach screenshot from CRM's SMS history tab showing no message found on transaction date<br><span class="important-note">NOTE:</span><br>- Request is assigned when a customer did not receive SMS alerts for their last 3 transactions<br>- Key Point: Only proceed with investigation when SMS is completely missing from the system history.`,
            "SMS Alert Serv. Not Active-CC": `<span class="important-note">Requirements:</span><br>- 1-Customer has their registered mobile number<br>- 2-Check SMS History in CRM:<br>- *If SMS appears in history (even with delivery status ""False"") → No action needed<br>- Bank system has sent the SMS, so issue is not from bank side<br>- *If SMS does NOT appear in history:<br>- Assign SMS Alert SR in CRM<br>- Open SD ticket directly<br>- Attach screenshot from CRM's SMS history tab showing no message found on transaction date<br><span class="important-note">NOTE:</span><br>- Request is assigned when a customer did not receive SMS alerts for their last 3 transactions<br>- Key Point: Only proceed with investigation when SMS is completely missing from the system history.`,
            "SocialMedia FX Limit Exception": "No more used.",
            "Stop Statement - Credit Card": "No more used",
            "Supplementary Referral - CC": `<span class="important-note">Requirements:</span><br>- For Supplementary Holder:<br>- National ID must be valid (14 digits)<br>- ID expiry must be at least next month (not expiring in current month)<br>- Embossed name must not exceed 26 characters<br>- For Primary Cardholder:<br>- Must have valid KYC<br>- - Must have registered address in CARD400 system  ( Shift+f8 ) + Enter + Enter + ( Shift+f5 ) <br>- Card must not be restricted → ( Shift+f8 ) → Risk category  : RES<br>- Card must not be expired<br>- Not in arrears for more than 30 days<br>- Not stopped due to missing travel documents or misuse<br>- Not VISA Business or COM cards<br>- TAT 10 WD<br><span class="important-note">NOTE:</span><br>- 1st and 2nd degree relatives only<br>- Not eligible: Brother-in-law and sister-in-law<br>- Supplementary holder must be over 15 years old<br>- Maximum 4 supplementary cards per SEMA level<br>- Closed cards with stoppage code 52 are excluded from count<br>- Heya cardholders can request male supplementary cards (will be printed as Titanium design)<br>- If customer changed card type: assign new supplementary request<br>- If customer changed card product: wait for primary card activation first<br>- For stopped supplementary cards: assign replacement request, not new request`,
            "Tele Sales Credit Card": `<span class="important-note">Requirements:</span><br>- Offer the New Credit Card<br><span class="important-note">NOTE:</span><br>- TAT 2 WD`,
            "Travel Documents": "Not assigned by CCA"
        },
        "SS EPP": {
            "EPP Partial Exception": "No more used"
        },
        "SS Loans": {
            "Loans Postponements-CBE-ACC": "No more used",
            "TeleSales - Mortgage": `<span class="important-note">Requirements:</span><br>- If the CM or Non CM asking for Mortgage <br><span class="important-note">NOTE:</span><br>- TAT 2 WD`
        },
        "SS Online": {
            "Hard Token Request": `<span class="important-note">Requirements:</span><br>- TAT ( 5WD )<br>- customer will receive it through CIB branch<br>- then he has to follow the below steps on his internet banking<br><span class="important-note">NOTE:</span><br>- hard token fees  (225 EGP)`,
            "IB Enable": `<span class="important-note">Requirements:</span><br>- Requesting to reactivate IB user name <br>- Must add the user name in the Description <br>-Customer must contact from his registered mobile number <br>- TAT 1 WD <br><span class="important-note">NOTE:</span><br>- this request in case the cm IB inactive or he/she requested to Close IB to lost him/her mobile not for Creating new IB`,
            "Reset IB Bad Login": "No more used",
            "SW Balance Transfer": `<span class="important-note">Requirements:</span><br>- 1-Same Customer: Both wallets must belong to the same customer with identical details (Full Name, National ID, Mobile Number).<br>- 2-No Holds: The old (unregistered) wallet must not have any hold amount at the time of the request.<br>- 3-Check All Wallets: The agent must check all of the customer's unregistered wallets. If multiple wallets have a balance, the agent must type the total sum of all amounts, including piastres (قروش).<br>- 4-Non-CIB Customers: If the customer is non-CIB, the agent must ensure the customer's profile has a National ID (NID). If not, the agent can amend the profile directly in CRM.<br><span class="important-note">NOTE:</span><br>- Agents can assign a ""SW Balance Transfer"" request to move a balance from an unregistered wallet to an active wallet, instead of emailing the back office.<br>- TAT: 3WDs`
        },
        "SS Others": {
            "Bonus Call": "No more used",
            "Business Banking Escalation": "Not assigned by CCA",
            "CCU Escalation": "No more used",
            "Captured Cards": `<span class="important-note">Requirements:</span><br>- Inform customer they will receive a call when card is located<br>- Mandatory Requirements:<br>- Agent must ask for last 4 digits of card<br>- If customer can't remember, mention ""CM can't remember last 4 digits"" in description (otherwise request will be cancelled)<br>- TAT: 1 week (request will be closed)<br><span class="important-note">NOTE:</span><br>- Captured Non-CIB Cards Only<br>- Customer name on card may differ in: spelling, spaces, or language from name confirmed in call<br>- Customer will be called once card is found in Central Vault sheets (Cairo/Alex) or from concerned branch feedback`,
            "Door Step Service": `<span class="important-note">Requirements:</span><br>- 1-Take the call from the registered number and confirm the service needed is one of the three listed on Note.<br>- 2- Check the system (T-24/CRM) to confirm the customer is flagged as a Senior Citizen or Disabled.<br>- 3-Inform the Customer: Advise them that their main branch will contact them to schedule the visit. Assure them the staff will show a CIB ID for verification.<br>- 4-Assign & Confirm: Submit the request in CRM, directing it to the customer's main branch. Remind the customer that the visit can only be to their registered address.<br><span class="important-note">NOTE:</span><br>- Purpose: To provide banking services at home for Senior Citizens (65+) and Disabled Customers.<br>- Eligible Services:<br>- KYC information updates.<br>- Activating dormant accounts (if the customer has no other active account).<br>- Account closure requests.`,
            "Escalation Call": `<span class="important-note">Requirements:</span><br>- Customer insists on contacting a Supervisor.<br>- Customer wants to investigate another agent for attitude, wrong information, etc.<br>- Smart Script must be used.<br>- Proper and detailed case description is required.<br>- In investigation cases, the CP# and the date & time of the original call are mandatory.<br><span class="important-note">NOTE:</span><br>- (TAT): X (To be determined based on internal policy).<br>- Prime & PLUS = Throughout the day if the order is placed before 4 PM.<br>- Wealth & Privat = 2 hours`,
            "Escalation Call to Quality": `<span class="important-note">Requirements:</span><br>- When to Assign:<br>- Waiver issues<br>- System/behavior issues (call placed on hold for more than 2 minutes, call dropped/disconnected, etc.)<br>- Agent attitude problems<br>- Incorrect information provided by the agent, but the issue was resolved by the CRU team  <br>*Used the below template*<br>Customer insist to assign request to hear the call regarding ( Cisco behavior - Agent Attitude-Waiver due to agent mistake -Wrong Info ).<br>• Date of Incident:<br>• Calling Party:<br>• Account / Fake Account: <br>• Copy of TRX (Transaction ID): <br>• Masked CC (If Applicable): <br>• Detailed Description of the Issue:<br>• Corrective Action Taken (if any):<br><span class="important-note">NOTE:</span><br>- This task is for the escalation team only.<br>- TAT :2 WD`,
            "Overseas Call": `<span class="important-note">Requirements:</span><br>- Overseas Coding Process<br><br>Egyptian Customer (with valid residency abroad)<br><br>If KYC and ID are valid, the agent should instruct the customer to send an email to<br>Overseas.Support@cibeg.com<br>, attaching their residency permit,<br>to be coded as Overseas.<br><br>Foreigner Customer<br><br>If requirements are met, the agent should also direct the customer to email<br>Overseas.Support@cibeg.com<br> requesting Overseas coding.<br><br>Egyptian Customer (resident abroad but no foreign address)<br><br>Agent should first help the customer change their mailing address<br>through the normal address update process over the call.<br><br>Then instruct the customer to send an email to<br>Overseas.Support@cibeg.com<br> attaching their residency permit.<br><br>If an Overseas Customer contacts the center for service<br><br>Only specific remote services are available per their segment<br>(list of services follows in the next section).<br><span class="important-note">NOTE:</span><br>- Callback Request (Wealth Coding)<br>- SLA:<br>- If Back Office receives the email from the Overseas Distribution Team before 2:00 p.m., processing will be same working day.<br>- If received after 2:00 p.m., it will be handled next working day.`,
            "PCA Verification": `<span class="important-note">Requirements:</span><br>- Call must be from the PCA's registered mobile number.<br>- PCA must verify: ( All this date on PCA sheet )<br>- Full name<br>- NID<br>- Ccomputer number<br>- Windows password.<br><span class="important-note">NOTE:</span><br>- Handle inquiries from a PCA (Private Customer Advisor) about their assigned private client.<br>- Assign the request under the customer’s profile, not the PCA’s profile.`,
            "Sales Referrals": `<span class="important-note">Requirements:</span><br>- Offer the loan<br>- Offer the Overdraft<br><span class="important-note">NOTE:</span><br>- TAT 2 WD`,
            "Waiver Task Acc. Number / CC": "Not assigned by CCA."
        },
        "SS Request": {
            "Add Sema On IB SR": "No more used",
            "Buy Out & Cash On Phone": `<span class="important-note">Requirements:</span><br>- We only assign this request if a customer or non-customer has another’s bank credit card and want us to settle his dues with the other bank. <br>- No criteria for this request.<br><span class="important-note">NOTE:</span><br>- TAT 3WD`,
            "Cash Pickup": "No more used",
            "Certificate Issuance": "No more used",
            "Hold Release - Account": `<span class="important-note">Requirements:</span><br>- The point of sale (POS) or transaction source must be CIB.<br>- The agent must check the transaction details in the IST system.<br>- The request should only be assigned if the transaction failed or there is a technical issue related to it<br><span class="important-note">NOTE:</span><br>- To release a held amount from a transaction when the customer complains about it.<br>- TAT: 3WD`,
            "Hold Release - Credit Card": `<span class="important-note">Requirements:</span><br>- The point of sale (POS) or transaction source must be CIB.<br>- The agent must check the transaction details in the IST system.<br>- The request should only be assigned if the transaction failed or there is a technical issue related to it<br><span class="important-note">NOTE:</span><br>- To release a held amount from a transaction when the customer complains about it.<br>- TAT: 3WD`,
            "Inactive Account": `<span class="important-note">Requirements:</span><br>- Receive & Verify Call: The call must be from the customer's registered mobile number.<br>- Validate Customer Data: The agent must check the following:<br>- Customer has a valid ID.<br>- Customer has another active account with the bank.<br>- Customer's KYC is valid.<br>-  (TAT): Same Day.<br><span class="important-note">NOTE:</span><br>- Take Action:<br><br>- If all validations are met: The agent activates the account in the T24 system (maker level) and then submits a request in the CRM for supervisor authorization.<br>- If any validation fails (invalid ID, no active account, or invalid KYC): The agent must apologize to the customer and advise them to visit the nearest branch.<br>- Escalate for Authorization: After creating the CRM request, the agent must immediately send the Service Request (SR) number to the Contact Center Operation Supervisors email group to be processed.`,
            "New Billing Cycle": `<span class="important-note">Requirements:</span><br>- If Customer has EPP it will be cancelled<br>- •Account Arrears level not exceed 30 days<br>- •Cannot apply on flagged account with override code<br>- •Can not apply to change between network Visa or Master or Vice Versa<br>- •Cannot apply in corporate products<br>- •Account agreement status should be 09 active card<br>- •Cannot apply for special products such as (Egypt Air – World –  Swype –  NooN – Cashback )<br>- •Cannot apply when old expiry date is less than 6 months <br>- No amounts on hold ( Hold to be released first to apply for the request )<br>-New Annual Fees will be applied.<br><span class="important-note">NOTE:</span><br>- Note :Any existing EPP will be cancelled when changing billing cycle <br>- Note2 :Credit Cards Billing Cycle:<br>-02   End of Month Date 30   Due Date   27 <br>-03   End of Month Date  30  Due Date    25<br>-08   End of Month Date  10  Due Date     5<br>-09   End of Month Date  20 Due Date   15<br>-10   End of Month Date 30 Due Date   15<br>-11  End of Month Date  30 Due Date   25<br>-15   End of Month Date 30 Due Date   15 <br>-13   End of Month Date  30 Due Date   10 `,
            "Payroll SMS": `<span class="important-note">Requirements:</span><br>-Suspended <br>-In Case customer meeting the criteria but not receiving SMS , please assign SD Ticket + CCU complaint. ((After agent validate CRM SMS History or Campaigns Tab on CRM)<br>-Salary SMS cannot be cancelled, same as any other bank’s SMS (Debit cards withdrawals/deposits/instapay….etc), the service is free of charge`,
            "Re-Allocation - Credit Card": `<span class="important-note">Requirements:</span><br>- Check System (Shift + F7): There is a negative (-ve) amount in either the Retail or Cash sub-account.<br>- Customer Reports: The customer receives a specific error when trying to make a transaction, indicating that the card limit is only available in a ""specific group"" (e.g., only for retail or only for cash).<br><span class="important-note">NOTE:</span><br>- In simple terms: Assign this request when the card's limit is ""stuck"" in the wrong category (retail/cash), showing a negative balance in one sub-account and preventing the customer from using their available credit normally.<br>-We don’t assign re-allocation requests any more. The card is re-allocated normally in the beginning of the new statement.`
        },
        "SS Sales Follow Up": {
            "Credit Card Opp. Follow Up": `<span class="important-note">Requirements:</span><br>- In the reference section, enter the reference number provided to the customer during the application.<br><span class="important-note">NOTE:</span><br>- Purpose: Allow customers to follow up on pending product applications credit cards`,
            "Loan Opp. Follow Up": `<span class="important-note">Requirements:</span><br>- In the reference section, enter the reference number provided to the customer during the application.<br><span class="important-note">NOTE:</span><br>- Purpose: Allow customers to follow up on pending product applications Loan`,
            "Over Draft Opp. Follow Up": `<span class="important-note">Requirements:</span><br>- In the reference section, enter the reference number provided to the customer during the application.<br><span class="important-note">NOTE:</span><br>- Purpose: Allow customers to follow up on pending product applications Over Draft`
        }
    }
};